format_version: 10
pipelines:
  expense-tf-destroy:
    group: Terraform
    materials:
      git-da613e5:
        git: https://github.com/saketh-devops-i1/expense-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:kaUXh+aq4HbGIWkVbqfqvA==:hsfXYjAh0KZQnLcgEt3F7+LWVkx0Ex/pxx2AgBw4SLc=
      
    stages:
    - DEV:
        fetch_materials: true
        environment_variables:
          env: dev
        approval:
          type: manual
        jobs:
          terraform-apply:
            tasks:
            - exec: {command: terraform, arguments: [ "init", "-backend-config=env-dev/state.tfvars" ], run_if: passed}
            - exec: {command: terraform, arguments: [ "destroy", "-var-file=env-dev/main.tfvars", "-auto-approve" ], run_if: passed}